// generated by cdk8s
import { ApiObject } from 'cdk8s';
import { Construct } from 'constructs';

/**
 * undefined
 *
 * @schema OtherCronTab
 */
export class OtherCronTab extends ApiObject {
  /**
   * Defines a "OtherCronTab" API object
   * @param scope the scope in which to define this object
   * @param name a scope-local name for the object
   * @param options configuration options
   */
  public constructor(scope: Construct, name: string, options: OtherCronTabOptions = {}) {
    super(scope, name, {
      ...options,
      kind: 'OtherCronTab',
      apiVersion: 'stable.example.com/v1',
    });
  }
}

/**
 * @schema OtherCronTab
 */
export interface OtherCronTabOptions {
  /**
   * @schema OtherCronTab#spec
   */
  readonly spec?: OtherCronTabSpec;

}

/**
 * @schema OtherCronTabSpec
 */
export interface OtherCronTabSpec {
  /**
   * @schema OtherCronTabSpec#cronSpec
   */
  readonly cronSpec?: string;

  /**
   * @schema OtherCronTabSpec#image
   */
  readonly image?: string;

  /**
   * @schema OtherCronTabSpec#replicas
   */
  readonly replicas?: number;

}

