name: Build
on:
  push:
    branches:
      - java-temp

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: jsii/superchain

    steps:
      - uses: actions/checkout@v2
      - name: installing dependencies
        run: |
          pip3 install pipenv
          yarn install
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: compile
        run: |
          tools/align-version.sh
          yarn build
      - name: unit tests
        run: yarn test
      - name: create bundle
        run: yarn package
      - name: integration tests
        run: yarn integ

